### ISSUE TITLE
Could not find calling stack trace element! when running with maven exec plugin

### ISSUE THREAD

**Issue by jhannes** [jhannes/logevents#40]
```
16:11:27 java.lang.RuntimeException: Could not find calling stack trace element!
16:11:27 	at org.logevents.LogEvent.getCallerLocation(LogEvent.java:257)
16:11:27 	at org.logevents.LogEvent.getSimpleCallerLocation(LogEvent.java:265)
16:11:27 	at org.logevents.formatting.ConsoleLogEventFormatter.apply(ConsoleLogEventFormatter.java:50)
16:11:27 	at org.logevents.observers.ConsoleLogEventObserver.doLogEvent(ConsoleLogEventObserver.java:76)
16:11:27 	at org.logevents.observers.AbstractFilteredLogEventObserver.logEvent(AbstractFilteredLogEventObserver.java:27)
16:11:27 	at org.logevents.observers.CompositeLogEventObserver.logEvent(CompositeLogEventObserver.java:33)
16:11:27 	at org.logevents.impl.LevelLoggingEventGenerator.log(LevelLoggingEventGenerator.java:87)
16:11:27 	at org.logevents.impl.LevelLoggingEventGenerator.log(LevelLoggingEventGenerator.java:33)
16:11:27 	at org.logevents.impl.JavaUtilLoggingAdapter.publish(JavaUtilLoggingAdapter.java:62)
16:11:27 	at java.logging/java.util.logging.Logger.log(Logger.java:979)
16:11:27 	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
16:11:27 	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
16:11:27 	at hudson.maven.ExecutedMojo.<init>(ExecutedMojo.java:110)
16:11:27 	at hudson.maven.Maven3Builder$MavenExecutionListener.recordExecutionTime(Maven3Builder.java:642)
```

**Comment by jhannes** [comment]
Haven't seen this again since java.util.logging was added to org.logevents.LogEvent#isLoggingClass
